(() => {
    "use strict";
    class RooftopRunnerApp {
        constructor(windowManager, notifications, sound) { this.windowManager = windowManager; this.notifications = notifications; this.sound = sound; this.save = new window.RooftopRunner.Save(); }
        open() { this.record = this.windowManager.create({ appId: "rooftop-runner", title: "Rooftop Runner", className: "rooftop-runner-window", content: this.view(), onMount: record => this.bind(record), onClose: () => this.stop() }); return this.record; }
        view() { const root = document.createElement("div"); root.className = "rooftop-runner-app"; root.innerHTML = `<canvas aria-label="Rooftop Runner game"></canvas><header class="runner-hud"><div><span>Score <b data-role="score">0</b></span><span>Coins <b data-role="coins">0</b></span><span>Distance <b data-role="distance">0m</b></span></div><div><span>Best <b data-role="best">0</b></span><span data-role="fps" hidden>60 FPS</span><button type="button" aria-label="Pause game" data-action="pause">Ⅱ</button><button type="button" aria-label="Game settings" data-action="settings">⚙</button></div></header><section class="runner-screen" data-role="screen"><div><p class="settings-eyebrow">TULIP ARCADE</p><h2>Rooftop Runner</h2><p>Run, jump, slide, and own the skyline.</p><button type="button" data-action="start">Start run</button><button type="button" class="runner-exit" data-action="exit">Exit</button></div></section><aside class="runner-settings" data-role="settings" hidden><header><h3>Run settings</h3><button type="button" data-action="settings">×</button></header><label>Music volume <input type="range" min="0" max="1" step=".05" data-setting="musicVolume"></label><label>Sound volume <input type="range" min="0" max="1" step=".05" data-setting="soundVolume"></label><label>Difficulty <select data-setting="difficulty"><option value="relaxed">Relaxed</option><option value="normal">Normal</option><option value="fast">Fast</option></select></label><label>Graphics <select data-setting="quality"><option value="high">High</option><option value="low">Battery saver</option></select></label><label class="runner-check"><input type="checkbox" data-setting="showFps"> Show FPS</label><label class="runner-check"><input type="checkbox" data-setting="muted"> Mute sounds</label><button type="button" class="runner-danger" data-action="reset">Reset progress</button></aside>`; return root; }
        async bind(record) {
            this.record = record; this.root = record.content.querySelector(".rooftop-runner-app"); this.settings = await this.save.loadSettings(); this.best = await this.save.loadHighScore(); this.audio = new window.RooftopRunner.Audio(this.sound, this.settings); this.ui = new window.RooftopRunner.UI(this.root); this.engine = new window.RooftopRunner.Engine({ canvas: this.root.querySelector("canvas"), onUpdate: state => this.update(state), onOver: state => this.gameOver(state) }); this.bindEvents(); this.syncSettings(); this.ui.update({ score: 0, coins: 0, distance: "0m", best: this.best.score, fps: 60, showFps: this.settings.showFps }); this.ui.showScreen("ready"); this.resizeObserver = new ResizeObserver(() => this.engine.draw()); this.resizeObserver.observe(this.root); this.engine.draw();
        }
        bindEvents() {
            this.root.addEventListener("click", event => { const action = event.target.closest("[data-action]")?.dataset.action; if (action === "start") this.start(); if (action === "pause") this.pause(); if (action === "settings") this.ui.toggleSettings(this.root.querySelector("[data-role=settings]").hidden); if (action === "exit") this.record.close(); if (action === "reset") this.resetProgress(); });
            this.root.addEventListener("change", event => { const key = event.target.dataset.setting; if (!key) return; this.settings[key] = event.target.type === "checkbox" ? event.target.checked : event.target.value; this.save.saveSettings(this.settings); });
            this.root.querySelector("canvas").addEventListener("pointerdown", event => { event.preventDefault(); this.startOrJump(); });
            let touchY = 0; this.root.querySelector("canvas").addEventListener("pointerdown", event => { touchY = event.clientY; }); this.root.querySelector("canvas").addEventListener("pointerup", event => { if (event.clientY - touchY > 42) this.engine.slide(); });
            this.keydown = event => { if (!this.record?.focused) return; if (event.code === "Space" || event.key === "ArrowUp") { event.preventDefault(); this.startOrJump(); } else if (event.key === "ArrowDown") { event.preventDefault(); this.engine.slide(); } else if (event.key === "Escape") this.pause(); }; window.addEventListener("keydown", this.keydown);
        }
        syncSettings() { this.root.querySelectorAll("[data-setting]").forEach(input => { input[input.type === "checkbox" ? "checked" : "value"] = this.settings[input.dataset.setting]; }); }
        async start() { await this.audio.unlock(); this.audio.click(); this.engine.start(); this.ui.hideScreen(); }
        startOrJump() { if (this.engine.state === "idle" || this.engine.state === "over") return this.start(); if (this.engine.jump()) this.audio.jump(); }
        pause() { const state = this.engine.togglePause(); if (state === "paused") this.ui.showScreen("paused"); else if (state === "playing") this.ui.hideScreen(); }
        update(state) { if (state.gained.length) this.audio.coin(); this.ui.update({ ...state, best: Math.max(this.best.score, state.score), showFps: this.settings.showFps }); }
        async gameOver(state) { this.audio.hit(); if (state.score > this.best.score) { this.best = state; await this.save.saveHighScore(state); this.notifications?.show("New Rooftop Runner high score!"); } await this.save.saveRun({ ...state, savedAt: new Date().toISOString() }); this.ui.update({ ...state, best: this.best.score, fps: this.engine.fps, showFps: this.settings.showFps }); this.ui.showScreen("over", state); }
        async resetProgress() { this.best = { score: 0, coins: 0, distance: 0 }; await this.save.saveHighScore(this.best); this.notifications?.show("Rooftop Runner progress reset"); this.ui.update({ score: 0, coins: 0, distance: "0m", best: 0, fps: 60, showFps: this.settings.showFps }); }
        stop() { this.engine?.stop(); this.resizeObserver?.disconnect(); window.removeEventListener("keydown", this.keydown); }
    }
    window.RooftopRunnerApp = RooftopRunnerApp;
})();
