/* Scene navigation, memory data, audio, letter animation, and light canvas atmosphere. */
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const memories=[
 {label:'I LOVE YOU',date:'I LOVE YOU',title:'The First Time You Made My Heart Smile',text:"I don't know if you realized it, but that moment changed something inside me. It wasn't dramatic or perfect—it was simply you being yourself. Somehow, that was enough to make my ordinary world feel brighter.",image:'assets/images/img1.jpg',x:17,y:49,color:'#e45767'},
 {label:'MY SAFE PLACE',date:'MY SAFE PLACE',title:'Every Conversation Felt Like Home',text:'No matter how difficult the day was, talking to you always made everything feel lighter. Your words became the place where my worries disappeared and my heart finally felt at peace.',image:'assets/images/img2.jpg',x:36,y:65,color:'#f59aae'},
 {label:'OUR LITTLE WORLD',date:'OUR LITTLE WORLD',title:'The Moments Only We Understand',text:"Every inside joke, every random conversation, every silly moment became tiny treasures. They may seem ordinary to everyone else, but to me they're chapters of the most beautiful story I've ever lived.",image:'assets/images/img3.jpg',x:56,y:47,color:'#f6c459'},
 {label:'MY FAVORITE PERSON',date:'MY FAVORITE PERSON',title:'The Smile I Could Never Forget',text:"Out of everything this world has to offer, your smile remains my favorite view. It's the kind of happiness that quietly stays in my mind long after the moment has passed.",image:'assets/images/img4.jpg',x:72,y:63,color:'#dc6572'},
 {label:'FOREVER STARTS HERE',date:'FOREVER STARTS HERE',title:'Thank You For Existing',text:"If I could relive one part of my life, I wouldn't choose a place or a day. I'd simply choose every moment that brought me closer to you. Thank you for becoming the most beautiful part of my story.",image:'assets/images/img5.jpg',x:29,y:82,color:'#ec7c8b'}];
const scenes={landing:$('#landing'),garden:$('#garden'),letter:$('#letterScene'),ending:$('#endingScene')};let current='landing';
function transition(to){if(to===current)return;document.body.classList.add('scene-transition');setTimeout(()=>{scenes[current].hidden=true;scenes[to].hidden=false;current=to;document.body.classList.remove('scene-transition');if(to==='ending')setTimeout(()=>{$('#fade').style.opacity='1';$('#fade').style.pointerEvents='auto'},8500)},820)}
function openModal(el){el.hidden=false;el.querySelector('.close-modal')?.focus()}function closeModal(el){el.hidden=true}
memories.forEach(m=>{const b=document.createElement('button');b.className='memory-tulip';b.style.cssText=`left:${m.x}%;top:${m.y}%;--color:${m.color}`;b.setAttribute('aria-label',`Open memory: ${m.title}`);b.innerHTML=`<small>${m.label}</small>`;b.onclick=()=>{$('#memoryDate').textContent=m.date;$('#memoryTitle').textContent=m.title;$('#memoryText').textContent=m.text;const image=$('#memoryImage');image.alt=m.title;image.style.cssText='object-fit:cover;border-radius:12px;transition:transform 1.8s ease';image.onload=()=>image.animate([{opacity:0,transform:'scale(1.035)'},{opacity:1,transform:'scale(1)'}],{duration:650,easing:'cubic-bezier(.2,.75,.25,1)',fill:'both'});image.src=m.image;openModal($('#memoryModal'))};$('#memoryMap').append(b)});
const memoryImage=$('#memoryImage');memoryImage.addEventListener('mouseenter',()=>memoryImage.style.transform='scale(1.045)');memoryImage.addEventListener('mouseleave',()=>memoryImage.style.transform='scale(1)');
$('#welcomeTulip').onclick=()=>{const flower=$('#welcomeTulip');flower.classList.add('opened');$('#walkHint').textContent='Welcome, Tanvi Verma';setTimeout(()=>transition('garden'),1400)};
$('#backToField').onclick=()=>transition('landing');$$('.chapter-stop').forEach(b=>b.onclick=()=>transition(b.dataset.stop));$$('.scene-back').forEach(b=>b.onclick=()=>transition(b.dataset.back));$('#benchButton').onclick=()=>{openModal($('#letterModal'));writeLetter()};$('#secretTulip').onclick=()=>{piano.pause();openModal($('#secretModal'))};$$('.close-modal').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal')));$$('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)closeModal(m)});
let written=false;function writeLetter(){const el=$('#letterBody');if(written)return;const text=el.textContent;el.textContent='';written=true;let i=0;(function ink(){el.textContent+=text[i++]||'';if(i<text.length)setTimeout(ink,14)})()}
const piano=$('#piano'),mute=$('#mute'),volume=$('#volume');piano.volume=.35;function beginSound(){piano.play().then(()=>mute.setAttribute('aria-pressed','false')).catch(()=>{})}beginSound();document.addEventListener('pointerdown',beginSound,{once:true});mute.onclick=()=>{piano.muted=!piano.muted;mute.setAttribute('aria-pressed',String(piano.muted));mute.textContent=piano.muted?'♩':'♫';if(!piano.muted)beginSound()};volume.oninput=()=>piano.volume=volume.value;
const canvas=$('#atmosphere'),ctx=canvas.getContext('2d');let dots=[];function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);dots=Array.from({length:Math.min(62,innerWidth/16)},(_,i)=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.3,vy:.1+Math.random()*.35,s:1+Math.random()*3,petal:i%6===0}))}addEventListener('resize',resize);resize();function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);dots.forEach(d=>{d.x+=d.vx+Math.sin(t/1700+d.y)*.15;d.y+=d.vy;if(d.x<-15)d.x=innerWidth+15;if(d.x>innerWidth+15)d.x=-15;if(d.y>innerHeight+15)d.y=-15;ctx.globalAlpha=d.petal?.42:.25;ctx.fillStyle=d.petal?'#ef8292':'#fffdf1';ctx.beginPath();ctx.ellipse(d.x,d.y,d.s,d.s*.55,t/1600,0,7);ctx.fill()});requestAnimationFrame(draw)}requestAnimationFrame(draw);
