(function () {
    const encoder = new TextEncoder(), decoder = new TextDecoder();
    const u16 = (a, o) => a[o] | a[o + 1] << 8, u32 = (a, o) => (a[o] | a[o + 1] << 8 | a[o + 2] << 16 | a[o + 3] << 24) >>> 0;
    const put16 = (a, o, n) => { a[o] = n; a[o + 1] = n >>> 8; }; const put32 = (a, o, n) => { put16(a, o, n); put16(a, o + 2, n >>> 16); };
    function crc32(bytes) { let c = -1; for (const b of bytes) { c ^= b; for (let i = 0; i < 8; i++) c = c >>> 1 ^ (c & 1 ? 0xedb88320 : 0); } return (c ^ -1) >>> 0; }
    async function inflate(bytes, method) { if (!method) return bytes; if (method !== 8 || !window.DecompressionStream) throw new Error("This ZIP uses compression not supported by this browser."); const stream = new Blob([bytes]).stream().pipeThrough(new DecompressionStream("deflate-raw")); return new Uint8Array(await new Response(stream).arrayBuffer()); }
    function parse(buffer) {
        const a = new Uint8Array(buffer), view = new DataView(a.buffer, a.byteOffset, a.byteLength); let eocd = -1;
        for (let i = a.length - 22; i >= Math.max(0, a.length - 65558); i--) if (u32(a, i) === 0x06054b50) { eocd = i; break; }
        if (eocd < 0) throw new Error("This is not a valid ZIP archive."); const count = u16(a, eocd + 10), start = u32(a, eocd + 16), files = []; let p = start;
        for (let i = 0; i < count; i++) { if (u32(a, p) !== 0x02014b50) throw new Error("The ZIP directory is corrupted."); const method = u16(a, p + 10), compressed = u32(a, p + 20), size = u32(a, p + 24), nameLength = u16(a, p + 28), extra = u16(a, p + 30), comment = u16(a, p + 32), offset = u32(a, p + 42), name = decoder.decode(a.slice(p + 46, p + 46 + nameLength)); files.push({ name, method, compressed, size, offset, directory: name.endsWith("/") }); p += 46 + nameLength + extra + comment; }
        return { bytes: a, files };
    }
    async function readFile(archive, file) { const p = file.offset, a = archive.bytes; if (u32(a, p) !== 0x04034b50) throw new Error(`Cannot read ${file.name}.`); const name = u16(a, p + 26), extra = u16(a, p + 28); return inflate(a.slice(p + 30 + name + extra, p + 30 + name + extra + file.compressed), file.method); }
    function makeZip(entries) { let offset = 0; const locals = [], central = []; entries.forEach(entry => { const name = encoder.encode(entry.name), data = entry.data, crc = crc32(data), local = new Uint8Array(30 + name.length + data.length); put32(local, 0, 0x04034b50); put16(local, 4, 20); put16(local, 8, 0); put32(local, 14, crc); put32(local, 18, data.length); put32(local, 22, data.length); put16(local, 26, name.length); local.set(name, 30); local.set(data, 30 + name.length); locals.push(local); const cd = new Uint8Array(46 + name.length); put32(cd, 0, 0x02014b50); put16(cd, 4, 20); put16(cd, 6, 20); put32(cd, 16, crc); put32(cd, 20, data.length); put32(cd, 24, data.length); put16(cd, 28, name.length); put32(cd, 42, offset); cd.set(name, 46); central.push(cd); offset += local.length; }); const cdSize = central.reduce((n, item) => n + item.length, 0), end = new Uint8Array(22); put32(end, 0, 0x06054b50); put16(end, 8, entries.length); put16(end, 10, entries.length); put32(end, 12, cdSize); put32(end, 16, offset); return new Blob([...locals, ...central, end], { type: "application/zip" }); }
    window.ArchiveManagerApp = class ArchiveManagerApp {
        constructor(windowManager, notifications) { this.windowManager = windowManager; this.notifications = notifications; }
        open(path = null) { const id = `archive-${Date.now()}`; this.windowManager.create({ appId: id, title: "🗜 Archive Manager", singleton: false, className: "archive-window", content: this.view(), onMount: record => this.bind(record, path) }); }
        view() { const root = document.createElement("div"); root.className = "archive-app"; root.innerHTML = '<div class="archive-toolbar"><button data-action="choose">Open ZIP</button><button data-action="compress">Compress folder</button><input data-role="picker" type="file" accept=".zip" hidden></div><div data-role="summary" class="archive-summary">Open a ZIP archive to preview or extract its contents.</div><div data-role="files" class="archive-files"></div><div data-role="progress" class="archive-progress" hidden><i></i><span></span><button data-action="cancel">Cancel</button></div>'; return root; }
        async bind(record, path) { const root = record.content.querySelector(".archive-app"); root.addEventListener("click", event => this.click(event, root)); root.querySelector("[data-role=picker]").addEventListener("change", event => this.choose(event, root)); if (path) await this.openPath(path, root); }
        async click(event, root) { const action = event.target.closest("[data-action]")?.dataset.action; if (action === "choose") root.querySelector("[data-role=picker]").click(); if (action === "compress") await this.compressPrompt(root); if (action === "extract") await this.extract(root); if (action === "cancel") this.cancelled = true; }
        async choose(event, root) { const file = event.target.files[0]; event.target.value = ""; if (!file) return; try { this.archive = parse(await file.arrayBuffer()); this.archiveName = file.name; this.render(root); } catch (error) { this.notifications.show(error.message, "error"); } }
        async openPath(path, root) { const entry = await window.TulipFS.get(path); if (!entry) throw new Error("Archive file is missing."); const value = entry.content; if (typeof value !== "string" || !value.startsWith("data:")) throw new Error("This archive cannot be opened."); const bytes = await fetch(value).then(response => response.arrayBuffer()); this.archive = parse(bytes); this.archiveName = path.split("/").pop(); this.render(root); }
        render(root) { const files = this.archive.files, original = files.reduce((n, file) => n + file.size, 0), compressed = files.reduce((n, file) => n + file.compressed, 0); root.querySelector("[data-role=summary]").innerHTML = `<strong>${this.archiveName}</strong><span>${files.length} files · ${this.bytes(compressed)} compressed · ${this.bytes(original)} original · ${original ? Math.round((1 - compressed / original) * 100) : 0}% saved</span><button data-action="extract">Extract to…</button>`; root.querySelector("[data-role=files]").replaceChildren(...files.map(file => { const row = document.createElement("div"); row.textContent = `${file.directory ? "📁" : "📄"} ${file.name} (${this.bytes(file.size)})`; return row; })); }
        async extract(root) { if (!this.archive) return; const destination = prompt("Extract to folder:", "/Downloads") || ""; if (!destination) return; const folder = destination.startsWith("/") ? destination : `/${destination}`; if (!(await window.TulipFS.get(folder))) await window.TulipFS.create(folder, "folder"); this.cancelled = false; const progress = root.querySelector("[data-role=progress]"), bar = progress.querySelector("i"), label = progress.querySelector("span"); progress.hidden = false; try { for (let i = 0; i < this.archive.files.length; i++) { if (this.cancelled) throw new Error("Extraction cancelled."); const file = this.archive.files[i], target = `${folder}/${file.name}`.replace(/\/+/g, "/"); if (file.directory) { if (!(await window.TulipFS.get(target))) await window.TulipFS.create(target, "folder"); } else { const existing = await window.TulipFS.get(target); if (existing && !confirm(`${file.name} already exists. Overwrite it?`)) continue; const bytes = await readFile(this.archive, file); await window.TulipFS.create(target, "file", decoder.decode(bytes)); } const percent = Math.round((i + 1) / this.archive.files.length * 100); bar.style.width = `${percent}%`; label.textContent = `Extracting ${percent}%`; await new Promise(resolve => setTimeout(resolve, 0)); } this.notifications.show("Archive extracted successfully."); } catch (error) { this.notifications.show(error.message, "error"); } finally { progress.hidden = true; } }
        async compressPrompt() { const folder = prompt("Folder to compress:", "/Documents"); if (!folder) return; const base = folder.replace(/\/$/, ""), root = await window.TulipFS.get(base); if (!root?.type || root.type !== "folder") throw new Error("Choose an existing folder."); const entries = (await window.TulipFS.list()).filter(item => item.path.startsWith(`${base}/`) && item.type !== "folder"); const zip = makeZip(entries.map(item => ({ name: item.path.slice(base.length + 1), data: encoder.encode(item.content || "") }))); const name = `${base.split("/").pop() || "archive"}.zip`; await window.TulipFS.create(`/Downloads/${name}`, "file", await new Promise(resolve => { const reader = new FileReader(); reader.onload = () => resolve(reader.result); reader.readAsDataURL(zip); })); this.notifications.show(`Archive created: ${name}`); }
        bytes(value) { return value < 1024 ? `${value} B` : `${(value / 1024).toFixed(1)} KB`; }
    };
})();
