(() => { "use strict";
class CameraApp {
 constructor(wm, notifications){this.wm=wm;this.notifications=notifications;this.stream=null;}
 open(){this.record=this.wm.create({appId:"camera",title:"📷 Camera",className:"camera-window",content:this.view(),onMount:r=>this.bind(r),onClose:()=>this.stop()});}
 view(){const root=document.createElement("div");root.className="camera-app";root.innerHTML='<video autoplay playsinline muted></video><canvas hidden></canvas><div class="camera-controls"><button data-action="switch">Flip</button><button data-action="capture" class="camera-capture" aria-label="Capture photo"></button><button data-action="save" disabled>Save photo</button></div><p data-status>Allow camera access to begin.</p>';return root;}
 async bind(record){this.root=record.content.querySelector(".camera-app");this.video=this.root.querySelector("video");this.canvas=this.root.querySelector("canvas");this.root.addEventListener("click",e=>this.action(e));await this.start("environment");}
 async start(facing){this.stop();this.facing=facing;try{this.stream=await navigator.mediaDevices?.getUserMedia({video:{facingMode:{ideal:facing}},audio:false});if(!this.stream)throw new Error("Camera access is unavailable");this.video.srcObject=this.stream;this.root.querySelector("[data-status]").textContent="Ready to capture";}catch(error){this.root.querySelector("[data-status]").textContent="Camera unavailable. Check browser permission.";this.notifications.show(error.message||"Unable to access camera","error");}}
 async action(event){const action=event.target.closest("[data-action]")?.dataset.action;if(action==="switch")await this.start(this.facing==="environment"?"user":"environment");if(action==="capture")this.capture();if(action==="save")await this.save();}
 capture(){if(!this.video.videoWidth)return;this.canvas.width=this.video.videoWidth;this.canvas.height=this.video.videoHeight;this.canvas.getContext("2d").drawImage(this.video,0,0);this.video.hidden=true;this.canvas.hidden=false;this.root.querySelector("[data-action=save]").disabled=false;this.root.querySelector("[data-status]").textContent="Preview ready";}
 async save(){try{const folder="/Pictures/Camera";const entries=await window.TulipFS.list();if(!entries.some(x=>x.path===folder))await window.TulipFS.create(folder,"folder");const stamp=new Date().toISOString().replace(/[:.]/g,"-");await window.TulipFS.create(`${folder}/Tulip-${stamp}.png`,"file",this.canvas.toDataURL("image/png"));this.notifications.show("Photo saved to Pictures/Camera");this.root.querySelector("[data-action=save]").disabled=true;}catch(error){this.notifications.show("Unable to save photo","error");console.error(error);}}
 stop(){this.stream?.getTracks().forEach(track=>track.stop());this.stream=null;}
} window.CameraApp=CameraApp;})();
