(() => { "use strict";
class ClockApp { constructor(wm,notifications){this.wm=wm;this.notifications=notifications;this.timer=0;this.stopwatch=0;this.elapsed=0;}
 open(){this.record=this.wm.create({appId:"clock",title:"🕰️ Clock",className:"clock-window",content:this.view(),onMount:r=>this.bind(r),onClose:()=>this.destroy()});}
 view(){const root=document.createElement("div");root.className="clock-app";root.innerHTML='<section class="clock-now"><div class="clock-analog"><i></i><b></b><em></em></div><div><strong data-time>00:00:00</strong><p data-date></p></div></section><section class="clock-tools"><div><h3>Alarm</h3><input data-alarm type="time"><button data-action="alarm">Set</button><p data-alarm-status>No alarm</p></div><div><h3>Stopwatch</h3><strong data-stopwatch>00:00.0</strong><button data-action="stopwatch">Start</button><button data-action="reset">Reset</button></div><div><h3>Timer</h3><input data-timer type="number" min="1" placeholder="Minutes"><button data-action="timer">Start</button><p data-timer-status></p></div></section><section><h3>World clock</h3><div class="world-clocks" data-world></div></section>';return root;}
 bind(record){this.root=record.content.querySelector(".clock-app");this.root.addEventListener("click",e=>this.action(e));this.tick();this.interval=setInterval(()=>this.tick(),100);}
 tick(){if(!this.root)return;const now=new Date();this.root.querySelector("[data-time]").textContent=now.toLocaleTimeString();this.root.querySelector("[data-date]").textContent=now.toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});const sec=now.getSeconds(),min=now.getMinutes();this.root.querySelector(".clock-analog i").style.transform=`rotate(${sec*6}deg)`;this.root.querySelector(".clock-analog b").style.transform=`rotate(${min*6+sec/10}deg)`;if(this.running)this.elapsed+=100;this.root.querySelector("[data-stopwatch]").textContent=this.format(this.elapsed);const alarm=this.alarm;if(alarm===now.toTimeString().slice(0,5)&&sec===0){this.notifications.show("Alarm");this.alarm="";this.root.querySelector("[data-alarm-status]").textContent="Alarm fired";}this.root.querySelector("[data-world]").replaceChildren(...["UTC","America/New_York","Europe/London","Asia/Kolkata","Asia/Tokyo"].map(zone=>{const el=document.createElement("div");el.textContent=`${zone.split("/").pop().replace("_"," ")} · ${now.toLocaleTimeString([],{timeZone:zone,hour:"2-digit",minute:"2-digit"})}`;return el;}));}
 action(e){const a=e.target.closest("[data-action]")?.dataset.action;if(a==="alarm"){this.alarm=this.root.querySelector("[data-alarm]").value;this.root.querySelector("[data-alarm-status]").textContent=this.alarm?`Set for ${this.alarm}`:"Choose a time";}if(a==="stopwatch"){this.running=!this.running;e.target.textContent=this.running?"Pause":"Start";}if(a==="reset")this.elapsed=0;if(a==="timer"){const value=Number(this.root.querySelector("[data-timer]").value);if(value>0){clearTimeout(this.timer);this.root.querySelector("[data-timer-status]").textContent=`Ends in ${value} minute(s)`;this.timer=setTimeout(()=>{this.notifications.show("Timer complete");this.root.querySelector("[data-timer-status]").textContent="Complete";},value*60000);}}}
 format(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60);return `${String(m).padStart(2,"0")}:${String(s%60).padStart(2,"0")}.${Math.floor(ms%1000/100)}`;} destroy(){clearInterval(this.interval);clearTimeout(this.timer);this.root=null;}
}window.ClockApp=ClockApp;})();
