(() => {
    "use strict";
    const SCORE_KEY = "tulip.flappy.high-score";
    class FlappyBirdApp {
        constructor(windowManager, notifications, sound) { this.windowManager = windowManager; this.notifications = notifications; this.sound = sound; }
        open() { this.record = this.windowManager.create({ appId: "flappy-bird", title: "🐦 Flappy Tulip", className: "flappy-window", content: this.view(), onMount: record => this.bind(record), onClose: () => this.stop() }); }
        view() { const root = document.createElement("div"); root.className = "flappy-app"; root.innerHTML = '<canvas aria-label="Flappy Bird game" width="420" height="560"></canvas><div class="flappy-hud"><span>Score <b data-score>0</b></span><span>Best <b data-best>0</b></span><button type="button" data-pause>Pause</button></div><div class="flappy-message" data-message><h2>Flappy Tulip</h2><p>Tap, click, or press Space to fly</p><button type="button" data-start>Start game</button></div>'; return root; }
        bind(record) { this.root = record.content.querySelector(".flappy-app"); this.canvas = this.root.querySelector("canvas"); this.ctx = this.canvas.getContext("2d"); this.root.querySelector("[data-best]").textContent = localStorage.getItem(SCORE_KEY) || "0"; this.root.querySelector("[data-start]").addEventListener("click", () => this.start()); this.root.querySelector("[data-pause]").addEventListener("click", () => this.togglePause()); this.canvas.addEventListener("pointerdown", event => { event.preventDefault(); this.flap(); }); this.keydown = event => { if ((event.code === "Space" || event.key === "ArrowUp") && this.record?.focused) { event.preventDefault(); this.flap(); } if (event.key.toLowerCase() === "p" && this.record?.focused) this.togglePause(); }; window.addEventListener("keydown", this.keydown); this.draw(); }
        start() { this.sound?.unlock(); this.state = "playing"; this.bird = { x: 90, y: 250, velocity: 0, radius: 15 }; this.pipes = []; this.score = 0; this.lastPipe = 0; this.lastFrame = performance.now(); this.root.querySelector("[data-score]").textContent = "0"; this.root.querySelector("[data-message]").hidden = true; cancelAnimationFrame(this.frame); this.frame = requestAnimationFrame(time => this.loop(time)); }
        flap() { if (this.state === "idle" || this.state === "over") return this.start(); if (this.state !== "playing") return; this.bird.velocity = -360; this.sound?.play("flap", "game"); }
        togglePause() { if (this.state === "playing") { this.state = "paused"; this.root.querySelector("[data-pause]").textContent = "Resume"; } else if (this.state === "paused") { this.state = "playing"; this.lastFrame = performance.now(); this.root.querySelector("[data-pause]").textContent = "Pause"; this.frame = requestAnimationFrame(time => this.loop(time)); } }
        loop(time) { if (this.state !== "playing") return; const dt = Math.min(.04, (time - this.lastFrame) / 1000); this.lastFrame = time; this.bird.velocity += 920 * dt; this.bird.y += this.bird.velocity * dt; if (time - this.lastPipe > 1450) { const gap = 145, top = 80 + Math.random() * 190; this.pipes.push({ x: 440, top, gap, scored: false }); this.lastPipe = time; } for (const pipe of this.pipes) { pipe.x -= 170 * dt; if (!pipe.scored && pipe.x + 58 < this.bird.x) { pipe.scored = true; this.score++; this.root.querySelector("[data-score]").textContent = this.score; this.sound?.play("score", "game"); } } this.pipes = this.pipes.filter(pipe => pipe.x > -70); if (this.collides()) return this.gameOver(); this.draw(); this.frame = requestAnimationFrame(next => this.loop(next)); }
        collides() { const b = this.bird; return b.y - b.radius < 0 || b.y + b.radius > 560 || this.pipes.some(p => b.x + b.radius > p.x && b.x - b.radius < p.x + 58 && (b.y - b.radius < p.top || b.y + b.radius > p.top + p.gap)); }
        gameOver() { this.state = "over"; this.sound?.play("hit", "game"); const best = Math.max(this.score, Number(localStorage.getItem(SCORE_KEY)) || 0); localStorage.setItem(SCORE_KEY, String(best)); this.root.querySelector("[data-best]").textContent = best; const message = this.root.querySelector("[data-message]"); message.hidden = false; message.querySelector("h2").textContent = `Score: ${this.score}`; message.querySelector("p").textContent = "Tap or press Space to try again"; message.querySelector("[data-start]").textContent = "Play again"; }
        draw() { const c = this.ctx, bird = this.bird || { x: 90, y: 250, radius: 15 }; c.clearRect(0, 0, 420, 560); const sky = c.createLinearGradient(0, 0, 0, 560); sky.addColorStop(0, "#75cef7"); sky.addColorStop(1, "#e7f7d8"); c.fillStyle = sky; c.fillRect(0, 0, 420, 560); c.fillStyle = "#74b94b"; for (const pipe of this.pipes || []) { c.fillRect(pipe.x, 0, 58, pipe.top); c.fillRect(pipe.x, pipe.top + pipe.gap, 58, 560); c.fillStyle = "#4f8d31"; c.fillRect(pipe.x - 5, pipe.top - 16, 68, 16); c.fillRect(pipe.x - 5, pipe.top + pipe.gap, 68, 16); c.fillStyle = "#74b94b"; } c.fillStyle = "#ffc933"; c.beginPath(); c.arc(bird.x, bird.y, bird.radius, 0, Math.PI * 2); c.fill(); c.fillStyle = "#fff"; c.beginPath(); c.arc(bird.x + 6, bird.y - 5, 5, 0, Math.PI * 2); c.fill(); c.fillStyle = "#222"; c.beginPath(); c.arc(bird.x + 8, bird.y - 5, 2, 0, Math.PI * 2); c.fill(); c.fillStyle = "#f47c3c"; c.fillRect(bird.x + 14, bird.y + 1, 11, 6); }
        stop() { cancelAnimationFrame(this.frame); window.removeEventListener("keydown", this.keydown); this.state = "idle"; }
    }
    window.FlappyBirdApp = FlappyBirdApp;
})();
