(() => { "use strict";
class MediaPlayerApp { constructor(wm,notifications){this.wm=wm;this.notifications=notifications;this.playlist=[];this.index=0;this.key="tulip.media.position";}
 async open(file){if(file)this.playlist=[file];this.record=this.wm.create({appId:"media-player",title:"🎵 Media Player",className:"media-player-window",content:this.view(),onMount:r=>this.bind(r),onClose:()=>this.destroy()});if(!file){const files=await window.TulipFS.list();this.playlist=files.filter(item=>window.TulipMedia?.isMedia(item));}this.render();}
 view(){const root=document.createElement("div");root.className="media-player";root.innerHTML='<div class="media-art">♫</div><h2 data-title>No media selected</h2><audio preload="metadata"></audio><input data-seek type="range" min="0" max="100" value="0"><div class="media-controls"><button data-action="previous">◀</button><button data-action="play">▶</button><button data-action="next">▶</button><button data-action="shuffle">Shuffle</button><button data-action="repeat">Repeat</button><input data-volume type="range" min="0" max="1" step=".05" value="1"></div><p data-time>0:00 / 0:00</p><div class="media-playlist" data-list></div>';return root;}
 bind(record){this.root=record.content.querySelector(".media-player");this.audio=this.root.querySelector("audio");this.root.addEventListener("click",e=>this.action(e));this.root.querySelector("[data-seek]").addEventListener("input",e=>{if(this.audio.duration)this.audio.currentTime=this.audio.duration*Number(e.target.value)/100;});this.root.querySelector("[data-volume]").addEventListener("input",e=>this.audio.volume=Number(e.target.value));this.audio.addEventListener("timeupdate",()=>this.progress());this.audio.addEventListener("ended",()=>this.next());this.audio.addEventListener("error",()=>this.notifications.show("Unable to play this media file","error"));}
 render(){if(!this.root)return;const file=this.playlist[this.index];const list=this.root.querySelector("[data-list]");list.replaceChildren(...this.playlist.map((item,i)=>{const b=document.createElement("button");b.dataset.index=i;b.classList.toggle("active",i===this.index);b.textContent=item.path.split("/").pop();return b;}));if(!file)return;this.root.querySelector("[data-title]").textContent=file.path.split("/").pop();this.audio.src=window.TulipMedia.sourceFor?.(file)||file.content;const saved=JSON.parse(localStorage.getItem(this.key)||"{}")[file.path];if(Number.isFinite(saved))this.audio.currentTime=saved;}
 action(e){const index=e.target.closest("[data-index]")?.dataset.index;if(index!==undefined){this.index=Number(index);this.render();return;}const a=e.target.closest("[data-action]")?.dataset.action;if(a==="play"){this.audio.paused?this.audio.play().catch(()=>this.notifications.show("Playback needs a user gesture","error")):this.audio.pause();e.target.textContent=this.audio.paused?"▶":"❚❚";}if(a==="next")this.next();if(a==="previous"){this.index=(this.index-1+this.playlist.length)%this.playlist.length;this.render();}if(a==="shuffle"){this.playlist.sort(()=>Math.random()-.5);this.index=0;this.render();}if(a==="repeat")this.audio.loop=!this.audio.loop;}
 next(){if(!this.playlist.length)return;this.index=(this.index+1)%this.playlist.length;this.render();this.audio.play().catch(()=>{});}progress(){const d=this.audio.duration||0;this.root.querySelector("[data-seek]").value=d?String(this.audio.currentTime/d*100):"0";this.root.querySelector("[data-time]").textContent=`${this.time(this.audio.currentTime)} / ${this.time(d)}`;try{const saved=JSON.parse(localStorage.getItem(this.key)||"{}");saved[this.playlist[this.index]?.path]=this.audio.currentTime;localStorage.setItem(this.key,JSON.stringify(saved));}catch{}}
 time(v){return Number.isFinite(v)?`${Math.floor(v/60)}:${String(Math.floor(v%60)).padStart(2,"0")}`:"0:00";}destroy(){this.audio?.pause();this.root=null;}
}window.MediaPlayerApp=MediaPlayerApp;})();
