(function () {
    class ShellSession {
        constructor(app, record) { this.app = app; this.record = record; this.cwd = "/"; this.history = app.loadHistory(); this.historyIndex = this.history.length; this.cancelled = false; }
        mount() { const root = this.record.content.querySelector(".terminal-app"); this.root = root; this.output = root.querySelector("[data-role=output]"); this.input = root.querySelector("input"); this.write("Tulip Shell", "terminal-banner-title"); this.write("Type help for commands. Files are stored in your TulipFS home.", "terminal-banner-copy"); this.updatePrompt(); root.querySelector("form").addEventListener("submit", event => { event.preventDefault(); this.submit(); }); this.input.addEventListener("keydown", event => this.key(event)); root.addEventListener("pointerdown", event => { if (!event.target.matches("input")) this.input.focus(); }); this.input.focus(); }
        write(text = "", cls = "") { const line = document.createElement("div"); line.className = `terminal-line ${cls}`; line.textContent = text; this.output.append(line); this.output.scrollTop = this.output.scrollHeight; }
        updatePrompt() { const path = this.cwd === "/" ? "~" : `~${this.cwd}`; this.root.querySelector("[data-role=prompt-path]").textContent = path; this.root.querySelector("[data-role=cwd]").textContent = this.cwd; }
        key(event) { if (event.ctrlKey && event.key.toLowerCase() === "l") { event.preventDefault(); this.output.replaceChildren(); } else if (event.ctrlKey && event.key.toLowerCase() === "c") { event.preventDefault(); this.cancelled = true; this.input.value = ""; this.write("^C", "terminal-muted"); } else if (event.key === "ArrowUp") { event.preventDefault(); this.input.value = this.history[Math.max(0, --this.historyIndex)] || ""; } else if (event.key === "ArrowDown") { event.preventDefault(); this.historyIndex = Math.min(this.history.length, this.historyIndex + 1); this.input.value = this.history[this.historyIndex] || ""; } else if (event.key === "Tab") { event.preventDefault(); this.complete(); } }
        async submit() { const command = this.input.value.trim(); if (!command) return; this.write(`tulip@${this.app.userName()}:${this.cwd === "/" ? "~" : `~${this.cwd}`}$ ${command}`, "terminal-command"); this.input.value = ""; if (this.history.at(-1) !== command) this.history.push(command); this.history = this.history.slice(-this.app.historyLimit()); this.app.saveHistory(this.history); this.historyIndex = this.history.length; this.cancelled = false; try { await this.execute(command); } catch (error) { this.write(error.message || "The command could not be completed.", "terminal-error"); this.app.notifications?.show(error.message || "Terminal error", "error"); } this.updatePrompt(); this.input.focus(); }
        tokens(command) { const result = []; command.replace(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g, token => (result.push(token.replace(/^("|')|("|')$/g, "")), token)); return result; }
        resolve(value = ".") { if (value === "~") return "/"; const raw = value.startsWith("/") ? value : `${this.cwd}/${value}`; const parts = []; raw.split("/").forEach(part => { if (!part || part === ".") return; if (part === "..") parts.pop(); else parts.push(part); }); return `/${parts.join("/")}`; }
        parent(path) { return path.substring(0, path.lastIndexOf("/")) || "/"; } basename(path) { return path.split("/").filter(Boolean).pop() || "/"; }
        async ensureParent(path) { const parent = this.parent(path); if (parent !== "/" && (await window.TulipFS.get(parent))?.type !== "folder") throw new Error(`No such folder: ${parent}`); }
        async execute(command) { const parts = command.split("|").map(part => part.trim()); let input = ""; for (const part of parts) input = await this.executeOne(part, input); if (input) this.write(input); }
        async executeOne(command, piped) { const redirect = command.match(/\s(>>|>)\s*([^\s]+)\s*$/); if (redirect) command = command.slice(0, redirect.index).trim(); const [name, ...args] = this.tokens(command); if (!name) return ""; const handler = this.handlers()[name]; if (!handler) throw new Error(`${name}: command not found`); const result = await handler(args, piped); const output = result === undefined ? "" : String(result); if (redirect) { const path = this.resolve(redirect[2]); await this.ensureParent(path); const old = redirect[1] === ">>" ? (await window.TulipFS.get(path))?.content || "" : ""; await window.TulipFS.create(path, "file", `${old}${output}${output ? "\n" : ""}`); return ""; } return output; }
        handlers() { return {
            help: () => "Filesystem: ls cd mkdir touch rm mv cp cat tree find\nApps: open run\nSystem: whoami hostname date time history shutdown restart\nShell: clear pwd echo help\nSupports |, >, >>, Tab, Up/Down, Ctrl+L and Ctrl+C.",
            clear: () => { this.output.replaceChildren(); return ""; }, pwd: () => this.cwd, echo: (args, piped) => args.length ? args.join(" ") : piped, whoami: () => this.app.userName(), hostname: () => "Tulip", date: () => new Date().toLocaleDateString(), time: () => new Date().toLocaleTimeString(), history: () => this.history.map((item, i) => `${String(i + 1).padStart(3)}  ${item}`).join("\n"),
            ls: args => this.ls(args[0]), cd: args => this.cd(args[0]), mkdir: args => this.mkdir(args[0]), touch: args => this.touch(args[0]), rm: args => this.rm(args), mv: args => this.mv(args), cp: args => this.cp(args), cat: args => this.cat(args[0]), tree: args => this.tree(args[0]), find: args => this.find(args[0], args[1]), open: args => this.open(args[0]), run: args => this.run(args[0]), shutdown: () => { document.getElementById("desktop").hidden = true; document.getElementById("boot-screen").hidden = false; return "Shutting down…"; }, restart: () => { location.reload(); return "Restarting…"; }
        }; }
        async ls(value) { const path = this.resolve(value || "."), item = path === "/" ? { type: "folder" } : await window.TulipFS.get(path); if (!item) throw new Error(`ls: ${path}: no such file or directory`); if (item.type !== "folder") return this.basename(path); const files = (await window.TulipFS.list()).filter(file => this.parent(file.path) === path).sort((a,b) => a.type === b.type ? a.path.localeCompare(b.path) : a.type === "folder" ? -1 : 1); return files.map(file => `${file.type === "folder" ? "📁" : "📄"} ${this.basename(file.path)}${file.type === "folder" ? "/" : ""}`).join("    ") || "(empty)"; }
        async cd(value) { const path = this.resolve(value || "/"), item = path === "/" ? { type: "folder" } : await window.TulipFS.get(path); if (item?.type !== "folder") throw new Error(`cd: ${path}: not a directory`); this.cwd = path; return ""; }
        async mkdir(value) { if (!value) throw new Error("Usage: mkdir <folder>"); const path = this.resolve(value); if (await window.TulipFS.get(path)) throw new Error("mkdir: already exists"); await this.ensureParent(path); await window.TulipFS.create(path, "folder"); return ""; }
        async touch(value) { if (!value) throw new Error("Usage: touch <file>"); const path = this.resolve(value), old = await window.TulipFS.get(path); if (old?.type === "folder") throw new Error("touch: is a directory"); await this.ensureParent(path); await window.TulipFS.create(path, "file", old?.content || ""); return ""; }
        async rm(args) { const recursive = args[0] === "-r" || args[0] === "-rf", value = args[recursive ? 1 : 0]; if (!value) throw new Error("Usage: rm [-r] <path>"); const path = this.resolve(value), item = await window.TulipFS.get(path); if (!item) throw new Error("rm: no such file or directory"); if (item.type === "folder" && !recursive) throw new Error("rm: is a directory (use rm -r)"); if (!(await window.TulipFS.delete(path, recursive))) throw new Error("rm: folder is not empty"); if (this.cwd === path || this.cwd.startsWith(`${path}/`)) this.cwd = this.parent(path); return ""; }
        async mv(args) { if (args.length < 2) throw new Error("Usage: mv <source> <destination>"); const from = this.resolve(args[0]); let to = this.resolve(args[1]); if ((await window.TulipFS.get(to))?.type === "folder") to += `/${this.basename(from)}`; if (!(await window.TulipFS.move(from, to))) throw new Error("mv: destination exists or is invalid"); return ""; }
        async cp(args) { if (args.length < 2) throw new Error("Usage: cp <source> <destination>"); const from = this.resolve(args[0]); let to = this.resolve(args[1]); if ((await window.TulipFS.get(to))?.type === "folder") to += `/${this.basename(from)}`; if (!(await window.TulipFS.copy(from, to))) throw new Error("cp: destination exists or is invalid"); return ""; }
        async cat(value) { if (!value) throw new Error("Usage: cat <file>"); const file = await window.TulipFS.get(this.resolve(value)); if (!file) throw new Error("cat: no such file"); if (file.type === "folder") throw new Error("cat: is a directory"); return file.content || ""; }
        async tree(value) { const root = this.resolve(value || "."), all = await window.TulipFS.list(), lines = [root]; const walk = (path, prefix) => all.filter(file => this.parent(file.path) === path).sort((a,b) => a.path.localeCompare(b.path)).forEach((file, index, list) => { const last = index === list.length - 1; lines.push(`${prefix}${last ? "└──" : "├──"} ${this.basename(file.path)}${file.type === "folder" ? "/" : ""}`); if (file.type === "folder") walk(file.path, `${prefix}${last ? "   " : "│  "}`); }); walk(root, ""); return lines.join("\n"); }
        async find(path, needle) { const base = this.resolve(path || "."), query = needle || ""; return (await window.TulipFS.list()).filter(file => file.path.startsWith(base) && this.basename(file.path).toLowerCase().includes(query.toLowerCase())).map(file => file.path).join("\n") || "No matching files."; }
        async open(value) { if (!value) throw new Error("Usage: open <file-or-folder>"); const path = this.resolve(value), file = await window.TulipFS.get(path); if (!file) throw new Error("open: no such file"); if (file.type === "folder") window.openFileExplorer?.(path); else if (path.toLowerCase().endsWith(".zip")) window.__tulipLauncher?.open("archive", path); else alert(file.content || "This file is empty."); return ""; }
        async run(name) { if (!name) throw new Error("Usage: run <app>"); window.__tulipLauncher?.open(name); return ""; }
        async complete() { const before = this.input.value.slice(0, this.input.selectionStart), tokens = this.tokens(before), current = tokens.at(-1) || "", first = tokens.length <= 1 && !/\s$/.test(before); let candidates; if (first) candidates = this.app.commands.filter(command => command.startsWith(current)); else { const slash = current.lastIndexOf("/"), dir = slash < 0 ? "." : current.slice(0, slash + 1), prefix = slash < 0 ? current : current.slice(slash + 1), folder = this.resolve(dir); candidates = (await window.TulipFS.list()).filter(file => this.parent(file.path) === folder && this.basename(file.path).startsWith(prefix)).map(file => `${dir === "." ? "" : dir}${this.basename(file.path)}${file.type === "folder" ? "/" : ""}`); } if (candidates.length === 1) { const start = before.length - current.length; this.input.value = `${this.input.value.slice(0,start)}${candidates[0]}${this.input.value.slice(this.input.selectionStart)}`; } else if (candidates.length) this.write(candidates.join("    "), "terminal-help"); }
    }
    window.TerminalApp = class TerminalApp { constructor(windowManager, notifications, users) { this.windowManager = windowManager; this.notifications = notifications; this.users = users; this.commands = ["help","clear","pwd","ls","cd","mkdir","touch","rm","mv","cp","cat","echo","whoami","hostname","history","tree","find","open","run","shutdown","restart","date","time"]; } historyKey() { return `tulip.terminalHistory.${this.users?.getActive().username || "admin"}`; } loadHistory() { try { const value = JSON.parse(localStorage.getItem(this.historyKey()) || "[]"); return Array.isArray(value) ? value : []; } catch { return []; } } saveHistory(history) { localStorage.setItem(this.historyKey(), JSON.stringify(history)); } historyLimit() { return Number(localStorage.getItem("tulip.terminalHistoryLimit") || 200); } userName() { return this.users?.getActive().username || "admin"; } open() { const id = `terminal-${Date.now()}`; this.windowManager.create({ appId: id, title: "⌘ Tulip Terminal", singleton: false, className: "terminal-window", content: '<div class="terminal-app"><div class="terminal-topbar"><span class="terminal-status"></span><span>Tulip shell</span><span data-role="cwd"></span></div><div class="terminal-output" data-role="output"></div><form class="terminal-prompt"><span class="terminal-user">tulip</span><span>:</span><span class="terminal-path" data-role="prompt-path">~</span><span>$</span><input type="text" autocomplete="off" spellcheck="false"><span class="terminal-cursor"></span></form></div>', onMount: record => new ShellSession(this, record).mount() }); } };
})();
